#!/usr/bin/env bash
# g++ 1.cc color_map.cc -o 1  -framework OpenGL -lglew -lglfw3 -g -O0 /  -l cxxsupport -Wno-deprecated-declarations -lcfitsio

HEALPIX_CXX_DIR=/Users/jaz/src/Healpix_3.11/src/cxx/

HEALPIX_INCLUDE="-I${HEALPIX_CXX_DIR}/Healpix_cxx/  -I${HEALPIX_CXX_DIR}/cxxsupport"
HEALPIX_LINK="-L${HEALPIX_CXX_DIR}/basic_gcc/lib/ -lhealpix_cxx -lcxxsupport -lc_utils -lcfitsio"
GL_FLAGS="-framework OpenGL"
CXXFLAGS="-g -O0 -Wno-deprecated-declarations -std=c++11"
LDFLAGS="${CXXFLAGS} ${GL_FLAGS} ${HEALPIX_LINK} -lglew -lglfw3"

g++ -c avr_object.cc ${CXXFLAGS} ${GL_FLAGS}
g++ -c avr_healpix.cc  ${CXXFLAGS} ${GL_FLAGS} ${HEALPIX_INCLUDE}
g++ -c avr_viewer.cc  ${CXXFLAGS} ${GL_FLAGS} ${HEALPIX_INCLUDE}
g++ -c main.cc  ${CXXFLAGS} ${GL_FLAGS} ${HEALPIX_INCLUDE}
g++ -c color_map.cc  ${CXXFLAGS}

g++ -o main main.o color_map.o avr_viewer.o avr_healpix.o avr_object.o ${GL_FLAGS} ${LDFLAGS}